### ISSUE TITLE
Unknown error occurred.

### ISSUE THREAD

**Issue by malrogers7** [joemcc-90/leeds-bins-hass#19]
Thank you so much for writing this, it sounds ideal.

I have added this repo to HACS and restarted Home Assistant.  I try adding this to HA as a new integration and get an 'unknown error' as the screenshot attached. It also restarts Home Assistant.

I can't see anything in the logs,  but not sure where to look for any logs for installation of this integration.

I'm running Home Assistant OS on Raspberry Pi. HA is on 2024.6.1.

Integration version installed is 20240613.01.

![Screenshot_20240616-161824~2](https://github.com/joemcc-90/leeds-bins-hass/assets/123991557/7c47237c-a329-4e9b-b478-0e5ed92e075c)

Many thanks for any help.

**Comment by Madders** [comment]
I'm also having this same issue, and the logs don't contain any information.

**Comment by joemcc-90** [comment]
Hi guys, sorry only just seeing this, not sure why i never saw it when raised. You should be able to generate some logs by going to home assistant > integrations > leeds bins > enable debug logging 

Then it should generate some logs into the normal home assistant logs ( you may have to press "load full logs" to see anything. Can you give it a try and let me know if you find anything?

**Comment by joemcc-90** [comment]
Also for info i am running 2024.7.2 at the moment, I tried a few different things and am not able to get the same error, I did make some changes back in June so wondering if its maybe not backwards compatible, can you confirm HA version you are running?

**Comment by malrogers7** [comment]
Hi.  Sorry, because it does not set up the integration, i don't think I can enable debug logging: it's not in the integration list. I tried it again just now and same issue. There's nothing in the logs, even loading full logs.
I'm on HA core version 2024.7.2. Thanks.

**Comment by joemcc-90** [comment]
Ok thanks, so i wonder if maybe something doesnt work on Raspberry Pi, I'm going to add some extra logging in the initial config flow part and set up and do a new release, will comment here when its ready

**Comment by malrogers7** [comment]
Hi

I saw an updated version on HACS and tried that. It still did the same unknown error and there's nothing in the logs that I can see.

I did find this in the Supervisor logs, but not sure it's massively helpful:

> 2024-07-19 07:34:05.581 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
2024-07-19 07:34:11.848 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...

**Comment by joemcc-90** [comment]
I tried a lot and cannot re-create this. Any luck with later versions of HA?

**Comment by malrogers7** [comment]
Sorry, I'd forgotten about this. I suspect it is something on the Pi. I've changed over to an Intel pc to run HAOS and I've just installed it fine, thank you.
