### ISSUE TITLE
Source data file is currently zero bytes

### ISSUE THREAD

**Issue by daernsinstantfortress** [joemcc-90/leeds-bins-hass#27]
Just an FYI, but the source data used by this integration (https://opendata.leeds.gov.uk/downloads/bins/dm_jobs.csv) has been returning zero bytes since the weekend. I've reported it and will update if I hear anything.

**Comment by daernsinstantfortress** [comment]
I've just had a very nice email back confirming that the batch job failed last Thursday and hasn't run since and they'll take a look at it today.

**Comment by joemcc-90** [comment]
seems to still be the same, i never got a reply to my email, have just sent another one.

Will maybe have to look into another data source when i get some time.

**Comment by daernsinstantfortress** [comment]
Yeah, was going to give it a couple of weeks and I'll drop an email back to chase. I suspect it'll get fixed at some point.

**Comment by daernsinstantfortress** [comment]
I see data in the file again....!
